export type WeaponId = 'bazooka' | 'grenade' | 'shotgun' | 'punch' | 'cluster' | 'bomblet' | 'sheep' | 'airstrike' | 'airbomb' | 'bat' | 'selfdestruct' | 'torch' | 'minigun' | 'holy';
export type WeaponKind = 'projectile' | 'hitscan' | 'melee' | 'walker' | 'strike' | 'self' | 'torch';

export interface WeaponDef {
  id: WeaponId;
  name: string;
  icon: string;
  blurb: string;
  kind: WeaponKind;
  /** Starting ammo per team; Infinity for unlimited. */
  ammo: number;
  /** Hold Space to charge power before firing. */
  charge: boolean;
  /** Shots per use (shotgun fires twice). */
  shots: number;
  minSpeed: number;
  maxSpeed: number;
  windInfluence: number;
  gravityScale: number;
  /** null = explode on contact; otherwise bounce with this restitution. */
  restitution: number | null;
  /** Seconds until detonation; 0 = no fuse. Walkers detonate when it runs out. */
  fuse: number;
  radius: number;
  damage: number;
  force: number;
  range: number;
  /** Melee: 'uppercut' launches victims skywards, 'swing' bats them away along the aim line. */
  knock?: 'uppercut' | 'swing';
  /** Hitscan bursts: bullets fired one after another, `interval` seconds apart, fanning by `spread` radians. */
  burst?: { count: number; interval: number; spread: number };
  /** Upward kick a hitscan hit adds, on top of the push along the shot. */
  lift?: number;
  /** Seconds between coming to rest and detonating, for projectiles that wait until they stop. */
  restFuse?: number;
  /** Every buddy inside the blast takes the full damage instead of less towards the edge. */
  flatDamage?: boolean;
  /** Air strikes: bombs dropped around the clicked target. */
  strike?: { weapon: WeaponId; count: number; spacing: number };
  /** Fragments released when this projectile explodes. */
  cluster?: { weapon: WeaponId; count: number; speed: number };
}

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  bazooka: {
    id: 'bazooka',
    name: 'Bazooka',
    icon: '🚀',
    blurb: 'Hold Space to charge. Wind pushes it hard. Boom on contact.',
    kind: 'projectile',
    ammo: Infinity,
    charge: true,
    shots: 1,
    minSpeed: 10,
    maxSpeed: 42,
    windInfluence: 1,
    gravityScale: 1,
    restitution: null,
    fuse: 0,
    radius: 2.8,
    damage: 50,
    force: 15,
    range: 0,
  },
  grenade: {
    id: 'grenade',
    name: 'Grenade',
    icon: '💣',
    blurb: 'Bouncy throw with a 3 second fuse. Barely cares about wind.',
    kind: 'projectile',
    ammo: Infinity,
    charge: true,
    shots: 1,
    minSpeed: 6,
    maxSpeed: 30,
    windInfluence: 0.3,
    gravityScale: 1,
    restitution: 0.45,
    fuse: 3,
    radius: 2.8,
    damage: 50,
    force: 15,
    range: 0,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    icon: '🔫',
    blurb: 'Two instant shots along the aim line.',
    kind: 'hitscan',
    ammo: 2,
    charge: false,
    shots: 2,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    fuse: 0,
    radius: 1,
    damage: 22,
    force: 7,
    range: 32,
    lift: 3,
  },
  minigun: {
    id: 'minigun',
    name: 'Minigun',
    icon: '🔩',
    blurb: 'A long rattling burst of 14 bullets that shoves victims right across the map.',
    kind: 'hitscan',
    ammo: 1,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    fuse: 0,
    radius: 0.45,
    damage: 5,
    force: 3.6,
    range: 40,
    // Enough kick to keep the victim airborne, so ground friction cannot soak up the shove.
    lift: 2.2,
    burst: { count: 14, interval: 0.1, spread: 0.05 },
  },
  punch: {
    id: 'punch',
    name: 'Garlic Punch',
    icon: '👊',
    blurb: 'Close-range uppercut that launches the victim skywards.',
    kind: 'melee',
    ammo: Infinity,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    fuse: 0,
    radius: 0.7,
    damage: 45,
    force: 15,
    range: 1.3,
    knock: 'uppercut',
  },
  bat: {
    id: 'bat',
    name: 'Baseball Bat',
    icon: '🏏',
    blurb: 'Home run! Less damage than a punch, but swats the victim far along the aim line.',
    kind: 'melee',
    ammo: 2,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    fuse: 0,
    radius: 0,
    damage: 25,
    force: 26,
    range: 1.4,
    knock: 'swing',
  },
  cluster: {
    id: 'cluster',
    name: 'Cluster Bomb',
    icon: '🧨',
    blurb: 'Red grenade with a 3 second fuse. Bursts into five bomblets of 10 damage each.',
    kind: 'projectile',
    ammo: 3,
    charge: true,
    shots: 1,
    minSpeed: 6,
    maxSpeed: 30,
    windInfluence: 0.3,
    gravityScale: 1,
    restitution: 0.45,
    fuse: 3,
    radius: 2.2,
    damage: 25,
    force: 11,
    range: 0,
    cluster: { weapon: 'bomblet', count: 5, speed: 9 },
  },
  holy: {
    id: 'holy',
    name: 'Holy Garlic Grenade',
    icon: '✨',
    blurb: 'Rolls to a stop, sings Hallelujah, then erupts in an enormous blast.',
    kind: 'projectile',
    ammo: 1,
    charge: true,
    shots: 1,
    minSpeed: 6,
    maxSpeed: 28,
    windInfluence: 0.3,
    gravityScale: 1,
    restitution: 0.25,
    fuse: 0,
    restFuse: 1.6,
    radius: 7,
    damage: 100,
    force: 24,
    range: 0,
  },
  bomblet: {
    id: 'bomblet',
    name: 'Bomblet',
    icon: '•',
    blurb: 'Cluster fragment; explodes on contact.',
    kind: 'projectile',
    ammo: 0,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0.2,
    gravityScale: 1,
    restitution: null,
    fuse: 0,
    radius: 1.4,
    damage: 10,
    force: 6,
    range: 0,
    flatDamage: true,
  },
  sheep: {
    id: 'sheep',
    name: 'Sheep',
    icon: '🐑',
    blurb: 'Space lets it hop off in small leaps; press Space again to blow it up.',
    kind: 'walker',
    ammo: 1,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 1,
    restitution: null,
    fuse: 10,
    radius: 4,
    damage: 75,
    force: 17,
    range: 0,
  },
  airstrike: {
    id: 'airstrike',
    name: 'Air Strike',
    icon: '✈️',
    blurb: 'Click on the map: a plane flies over and drops five bombs around that spot.',
    kind: 'strike',
    ammo: 1,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    fuse: 0,
    radius: 2.4,
    damage: 25,
    force: 10,
    range: 0,
    strike: { weapon: 'airbomb', count: 5, spacing: 1.7 },
  },
  airbomb: {
    id: 'airbomb',
    name: 'Air Bomb',
    icon: '•',
    blurb: 'Air strike bomb; explodes on contact.',
    kind: 'projectile',
    ammo: 0,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0.15,
    gravityScale: 1,
    restitution: null,
    fuse: 0,
    radius: 2.4,
    damage: 25,
    force: 10,
    range: 0,
  },
  torch: {
    id: 'torch',
    name: 'Blowtorch',
    icon: '🔥',
    blurb: 'Walks forward for 3 seconds, burning a tunnel through the rock ahead. No climbing.',
    kind: 'torch',
    ammo: 2,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    // Burn duration in seconds.
    fuse: 3,
    // Tunnel radius.
    radius: 0.8,
    damage: 15,
    force: 7,
    range: 0.9,
  },
  selfdestruct: {
    id: 'selfdestruct',
    name: 'Self-Destruct',
    icon: '💥',
    blurb: 'The buddy blows itself up: damage equals its health, and the blast grows with it.',
    kind: 'self',
    ammo: 1,
    charge: false,
    shots: 1,
    minSpeed: 0,
    maxSpeed: 0,
    windInfluence: 0,
    gravityScale: 0,
    restitution: null,
    fuse: 0,
    // Scaled by the buddy's health when used: radius = hp / 10, damage = hp.
    radius: 10,
    damage: 100,
    force: 22,
    range: 0,
  },
};

/** Weapons a player can select, in hotkey order (1, 2, 3, …). Fragments are not listed. */
export const WEAPON_ORDER: readonly WeaponId[] = ['bazooka', 'grenade', 'shotgun', 'punch', 'cluster', 'sheep', 'airstrike', 'bat', 'torch', 'selfdestruct', 'minigun', 'holy'];
export const WEAPON_IDS = Object.keys(WEAPONS) as WeaponId[];
